name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['2.7.6', '3.1.1']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
